version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '4001:4001'
        volumes:
            - ./backend:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        depends_on:
            - backend
