version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '4001:4001'
        environment:
            - NODE_ENV=production
            - DATABASE_URL=${DATABASE_URL}
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:4001/health']
            interval: 30s
            timeout: 10s
            retries: 3

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        environment:
            - NODE_ENV=production
            - NEXT_PUBLIC_API_URL=http://localhost:4001
            - CHAT_WEBHOOK=${CHAT_WEBHOOK}
        depends_on:
            backend:
                condition: service_healthy
        restart: unless-stopped
