version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - '4001:4001'
        environment:
            - NODE_ENV=production
        restart: always

    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - '3001:3001'
        environment:
            - NODE_ENV=production
        restart: always
