version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '4001:4001'
        environment:
            - NODE_ENV=production
            - DATABASE_URL=${DATABASE_URL}
        restart: always

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        environment:
            - NODE_ENV=production
            - API_URL=http://localhost:4001
            - CHAT_WEBHOOK=${CHAT_WEBHOOK}
        restart: always
