POST https://n8n.gasatec.com.br/webhook-test/f6adef63169a93a45b04db6cccbe34cd
Content-Type: application/json

{
  "chatId": "123456",
  "mensagem": "Voce trabalha com desenvolvimento de software para mobile ??"
}